{% set name = "warlock" %}
{% set version = "1.3.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "d7403f728fce67ee2f22f3d7fa09c9de0bc95c3e7bcf6005b9c1962b77976a06" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - jsonschema >=0.7,<3
    - jsonpatch >=0.10,<2
    - six

test:
  imports:
    - {{ name }}

about:
  home: http://github.com/bcwaldon/warlock
  license: Apache 2.0
  summary: 'Python object model built on JSON schema and JSON patch.'

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
