{% set name = "warlock" %}
{% set version = "1.3.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a093c4d04b42b7907f69086e476a766b7639dca50d95edc83aef6aeab9db2090

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - jsonschema >=0.7,<4
    - jsonpatch >=0.10,<2
    - six

test:
  imports:
    - warlock

about:
  home: http://github.com/bcwaldon/warlock
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Python object model built on JSON schema and JSON patch.'

extra:
  recipe-maintainers:
    - anguslees
    - tschoonj
