travis:
  secure:
    BINSTAR_TOKEN: Mh4iRhLOfjnGZtKbA+bKA7kPdxaxcLwvP3j8p6+5EfQdWzSMrLBtQLJWkHZhiMvHWn3r6x9AMmHunWwDauTUKlXEKaDfayi9JX3TUime0o2FtRF7OILasxw+v1c3m9q8JBjlHHnWZVnoWGVOsnd/AAAswx1CoGKac4BV0KMHnz3bTcmmU6DEIERwva7v+0+fsE0nLbOdPZFGGXgIM/ykmGitaK4tRLLosPg5J7u3laF3t8rxbbHIvX1EPLp69B8x+A0c2pKam3uNwoaL9XeI5PV54XGZsutla17Pirgck0YKZQIl/EPwtGblp+Kp7h/a0bOYsKdOALuvKGhDsiUV4tR0qB4onFnm8aCJa1eAhp2gSDOgeLX5Xvx9Ezfc04oQHMJG49VYKvmb+Hss3zmL7izY6C++orgjclbBGD2ZY6PdEwE27Q8nFGUL8lhVnOAHVHvsNVom5BVEpe2TX1ldWyhmNCBjndoDMSoeI6ugiMmfDMPddfeXQ/79AM7TRUyKsd0B7wrfdR7GpQ4iOBWsO3/aBGIiLVohE6PhUIBG0WRuljPJs2oyPItfvbtqDq09JG3Zh4Oh0YbTHUWF/FSA1A5H+zSBu9JQ687gxPB4NRGwAgZK/Z+VMAxYtBNrKR6B+gYtgOmukUCZEJHPaMihty4ZNH8YN1E7dsQmDe3OrN8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
