travis:
  secure:
    BINSTAR_TOKEN: IFrI6/eEjOiowzD6akD7xu1SJS0i5glrA6AWEweW34jB+1Po1eJPyZhJSln165bLgoVrfwAQun6Jho5MEt+GZuX+zY9/jWsIT0WushGRCbWiJ5RYsRLKuI8+rD4DjyoVEt5REeoeblI32tdRW+Emze21fcY/n8lqA6urjaDvCYNFkA1LRaTjo3W2H9RyXptLYIzpH3Qm8I+9fEvj/9QT7smLmZ3E5jMSHjcBwC9PPfGORapX9m5+r8D8zAM6E6gPTK0vv/K4r0cbgIEhn6giF9Ccv60jOpB6YhYH/oB1gouqYHtpyYfsRbFlzom7rPM8PbPsWLIlx1Qe1EEQO6vpHmREjAgD9MVu3dg14arhyjiLx7dF5BvihvArarV1ibL7AtJ4qIxONYqY/cxI3shZLh3owO21Q/T9stItrlGJ6C1UQ5brKHwf17S3AlUNLRzwag6KQ7LLUhlMwOwWrmbYVK+8UWMBXB7tkADZfN0mUDTVUQ5oEKHRnE9jnmmfhsac0qhrsgy2Ab/t12IXrdnt5ocEdGFZqdogntZfqNNVv5YNkhqEa+/J1ZI5QkNjaJUcOJQxUNE++fxbxQbFCKowJyDmsZYi5JZtPewxzDYsKyMsRJ/+6YTwuz/hNOW0vgD3fBePCPo0NdUtpGcVu8JwmwjH7XMWtWsELU5mC5ZxWZY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
