travis:
  secure:
    BINSTAR_TOKEN: UUDqQ0wqCRmBJamTwucZvHkgOz6ZgxO8RKdS8SlqjHW4V0nFsA3eKkO/P2hZLpeyv90zrXsmE9Gnnsn5Our8C6UIAhEMhKjz8AjjSmn+vRr39CdsRulvQLU0QLFvauG8d/cDFBBf9XZFgxY6ZdKpG621feU1y6mUCjfSr2O/KRhgqbzMiC7JL9H2nyB8PbvQ8aD7UUtBe3wda/a9ooR8I6L2qKwLoa/4ajUrRPXqINTCkfskw9sbeOSB2m1miIsRFCX8Eusw74zFIQnejhVTCN+xxYbDEA+7JNVuFs7M/XZbGD4397bAWwnM3ELB0CpqLWrvIw9Yb8LDf2mo7Lt/ZZq9CCc5hz/FwdifeYefWCJrCstnynwBQzqCpNswaTb8SeTCL1y5lCSSikw2/M2V+jnIG3DVUwe5+b9SULqRti1sd9yegNdPgzPY6ZSf2y+2XWqTJ/F+hdZk9vuRZMsJQaPPKwNFGnX/CHfa1dE2z3JHXOzV1hgIsCo2U3FswJV/ECJtlQDZUoqcTSxbo/cEPZnK5OKo2+jb33qsf1oJs2EjSIUlQMl7+RVYflKP95PzzK6PJKj3mwrbtQE6TdMHJBV0p4C+ca/RLT8pDWg2sNMsK9WH4wCYMsNq/63wW58GqgfHp3NkYm3J84OqFN0dwbq14COlf6Ca2OwUr8suJKE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
